const express = require('express');
const router = express.Router();
const { auth, requireRole } = require('../middleware/auth');
const { Stocktake, StocktakeItem, Inventory, Product, Warehouse, Transaction, User, sequelize, Sequelize } = require('../models');
const { asyncHandler } = require('../middleware/errorHandler');
const { BadRequestError, NotFoundError } = require('../errors/AppError');
const logger = require('../utils/logger');

const { Op } = Sequelize;

// 获取盘库列表
router.get('/', auth, asyncHandler(async (req, res) => {
  const { page = 1, limit = 10, status, warehouse, keyword, startDate, endDate } = req.query;
  const where = {};

  if (status) where.status = status;
  if (warehouse) where.warehouseId = warehouse;
  if (keyword) {
    where[Op.or] = [
      { stocktakeNo: { [Op.like]: `%${keyword}%` } },
      { title: { [Op.like]: `%${keyword}%` } },
    ];
  }
  if (startDate && endDate) {
    where.createdAt = {
      [Op.gte]: new Date(startDate),
      [Op.lte]: new Date(endDate),
    };
  }

  const offset = (page - 1) * limit;
  const { count: total, rows: stocktakes } = await Stocktake.findAndCountAll({
    where,
    include: [
      { model: Warehouse, as: 'warehouse', attributes: ['id', 'name'], required: false },
      { model: User, as: 'creator', attributes: ['realName', 'username'], required: false },
      { model: User, as: 'firstConfirmer', attributes: ['realName', 'username'], required: false },
      { model: User, as: 'secondConfirmer', attributes: ['realName', 'username'], required: false },
    ],
    order: [['createdAt', 'DESC']],
    limit: parseInt(limit),
    offset,
  });

  res.json({
    stocktakes,
    pagination: {
      page: parseInt(page),
      limit: parseInt(limit),
      total,
      pages: Math.ceil(total / limit),
    },
  });
}));

// 获取盘库详情
router.get('/:id', auth, asyncHandler(async (req, res) => {
  const stocktake = await Stocktake.findByPk(req.params.id, {
    include: [
      { model: Warehouse, as: 'warehouse', attributes: ['name', 'address'], required: false },
      { model: User, as: 'creator', attributes: ['realName', 'username'], required: false },
      { model: User, as: 'firstConfirmer', attributes: ['realName', 'username'], required: false },
      { model: User, as: 'secondConfirmer', attributes: ['realName', 'username'], required: false },
      {
        model: StocktakeItem,
        as: 'items',
        include: [
          { model: Product, as: 'product', attributes: ['name', 'sku', 'spec', 'unit', 'price'], required: false },
        ],
      },
    ],
  });

  if (!stocktake) {
    throw new NotFoundError('盘库记录不存在');
  }

  res.json({ stocktake });
}));

// 创建盘库单
router.post('/', auth, requireRole(['admin', 'manager', 'warehouse_keeper']), asyncHandler(async (req, res) => {
  const { title, warehouse, remark } = req.body;

  if (!title || !warehouse) {
    throw new BadRequestError('标题和仓库不能为空');
  }

  const warehouseExists = await Warehouse.findByPk(warehouse);
  if (!warehouseExists) {
    throw new BadRequestError('仓库不存在');
  }

  await sequelize.transaction(async (t) => {
    // Get all inventory for this warehouse
    const inventories = await Inventory.findAll({
      where: { warehouseId: warehouse },
      include: [
        { model: Product, as: 'product', attributes: ['name', 'sku', 'spec', 'unit', 'price'], required: false },
      ],
      transaction: t,
    });

    // Create stocktake record (stocktakeNo auto-generated by hook)
    const stocktake = await Stocktake.create({
      title,
      warehouseId: warehouse,
      warehouseName: warehouseExists.name,
      startTime: new Date(),
      createdBy: req.user.id,
      remark,
      status: 'draft',
    }, { transaction: t });

    // Create items
    const items = inventories.map(inv => {
      const systemQuantity = inv.quantity;
      return {
        stocktakeId: stocktake.id,
        productId: inv.productId,
        sku: inv.product?.sku || '',
        productName: inv.product?.name || '',
        spec: inv.product?.spec || '',
        unit: inv.product?.unit || '',
        systemQuantity,
        actualQuantity: 0,
        difference: -systemQuantity,
        differenceType: 'loss',
        unitPrice: inv.product?.price || 0,
        totalAmount: -systemQuantity * (inv.product?.price || 0),
      };
    });

    if (items.length > 0) {
      await StocktakeItem.bulkCreate(items, { transaction: t });
    }

    await stocktake.reload({
      include: [{ model: StocktakeItem, as: 'items' }],
      transaction: t,
    });

    res.json({ stocktake, message: '盘库单创建成功' });
  });
}));

// 更新盘库单（录入实际库存）
router.put('/:id', auth, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { items, remark } = req.body;

  const stocktake = await Stocktake.findByPk(id);
  if (!stocktake) {
    throw new NotFoundError('盘库记录不存在');
  }

  if (stocktake.status !== 'draft') {
    throw new BadRequestError('只能编辑草稿状态的盘库单');
  }

  await sequelize.transaction(async (t) => {
    // Delete existing items
    await StocktakeItem.destroy({
      where: { stocktakeId: id },
      transaction: t,
    });

    // Calculate totals
    let totalProfitQuantity = 0;
    let totalProfitAmount = 0;
    let totalLossQuantity = 0;
    let totalLossAmount = 0;

    const updatedItems = items.map(item => {
      const difference = item.actualQuantity - item.systemQuantity;
      let differenceType = 'none';

      if (difference > 0) {
        differenceType = 'profit';
        totalProfitQuantity += difference;
        totalProfitAmount += difference * item.unitPrice;
      } else if (difference < 0) {
        differenceType = 'loss';
        totalLossQuantity += Math.abs(difference);
        totalLossAmount += Math.abs(difference) * item.unitPrice;
      }

      return {
        ...item,
        stocktakeId: id,
        difference,
        differenceType,
        totalAmount: difference * item.unitPrice,
      };
    });

    // Insert new items
    if (updatedItems.length > 0) {
      await StocktakeItem.bulkCreate(updatedItems, { transaction: t });
    }

    // Update stocktake totals
    stocktake.totalProfitQuantity = totalProfitQuantity;
    stocktake.totalProfitAmount = totalProfitAmount;
    stocktake.totalLossQuantity = totalLossQuantity;
    stocktake.totalLossAmount = totalLossAmount;
    if (remark !== undefined) stocktake.remark = remark;

    await stocktake.save({ transaction: t });

    await stocktake.reload({
      include: [{ model: StocktakeItem, as: 'items' }],
      transaction: t,
    });

    res.json({ stocktake, message: '盘库单更新成功' });
  });
}));

// 提交盘库单（进入核实流程）
router.post('/:id/submit', auth, asyncHandler(async (req, res) => {
  const { id } = req.params;

  const stocktake = await Stocktake.findByPk(id);
  if (!stocktake) {
    throw new NotFoundError('盘库记录不存在');
  }

  if (stocktake.status !== 'draft') {
    throw new BadRequestError('只能提交草稿状态的盘库单');
  }

  stocktake.status = 'confirming';
  await stocktake.save();

  res.json({ message: '盘库单已提交，等待核实' });
}));

// 核实盘库单 - 双人核实
router.post('/:id/confirm', auth, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { remark } = req.body;

  const stocktake = await Stocktake.findByPk(id, {
    include: [{ model: StocktakeItem, as: 'items' }],
  });

  if (!stocktake) {
    throw new NotFoundError('盘库记录不存在');
  }

  if (stocktake.status !== 'confirming') {
    throw new BadRequestError('盘库单不在核实状态');
  }

  // First confirmer
  if (!stocktake.firstConfirmedBy) {
    stocktake.firstConfirmedBy = req.user.id;
    stocktake.firstConfirmedAt = new Date();
    stocktake.firstConfirmedRemark = remark || '';
    await stocktake.save();
    return res.json({ message: '第一核实人确认成功，等待第二核实人确认' });
  }

  // Second confirmer
  if (!stocktake.secondConfirmedBy) {
    if (stocktake.firstConfirmedBy === req.user.id) {
      throw new BadRequestError('第二核实人不能与第一核实人相同');
    }

    await sequelize.transaction(async (t) => {
      stocktake.secondConfirmedBy = req.user.id;
      stocktake.secondConfirmedAt = new Date();
      stocktake.secondConfirmedRemark = remark || '';
      stocktake.status = 'completed';
      stocktake.completedBy = req.user.id;
      stocktake.completedAt = new Date();
      stocktake.endTime = new Date();

      // Update inventory and create transactions for differences
      for (const item of stocktake.items) {
        if (item.difference !== 0) {
          // Update inventory
          await Inventory.increment(
            { quantity: item.difference },
            {
              where: { productId: item.productId, warehouseId: stocktake.warehouseId },
              transaction: t,
            }
          );

          await Inventory.update(
            { lastUpdated: new Date(), updatedBy: req.user.id },
            {
              where: { productId: item.productId, warehouseId: stocktake.warehouseId },
              transaction: t,
            }
          );

          // Create transaction record
          const transactionType = item.difference > 0 ? 'stocktake_profit' : 'stocktake_loss';
          await Transaction.create({
            type: transactionType,
            productId: item.productId,
            warehouseId: stocktake.warehouseId,
            quantity: Math.abs(item.difference),
            price: item.unitPrice,
            unitPrice: item.unitPrice,
            referenceNo: stocktake.stocktakeNo,
            remark: `盘库${item.differenceType === 'profit' ? '盘盈' : '盘亏'}：${item.productName}`,
            operator: req.user.id,
            createdBy: req.user.id,
            status: 'completed',
          }, { transaction: t });
        }
      }

      await stocktake.save({ transaction: t });
    });

    return res.json({ message: '第二核实人确认成功，盘库完成，库存已更新' });
  }

  throw new BadRequestError('盘库单已完成核实');
}));

// 取消盘库单
router.post('/:id/cancel', auth, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { reason } = req.body;

  if (!reason) {
    throw new BadRequestError('取消原因不能为空');
  }

  const stocktake = await Stocktake.findByPk(id);
  if (!stocktake) {
    throw new NotFoundError('盘库记录不存在');
  }

  if (stocktake.status === 'completed') {
    throw new BadRequestError('已完成的盘库单不能取消');
  }

  stocktake.status = 'cancelled';
  stocktake.cancelledBy = req.user.id;
  stocktake.cancelledAt = new Date();
  stocktake.cancelReason = reason;

  await stocktake.save();

  res.json({ message: '盘库单已取消' });
}));

// 导出盘库报表
router.get('/:id/export', auth, asyncHandler(async (req, res) => {
  const { id } = req.params;

  const stocktake = await Stocktake.findByPk(id, {
    include: [
      { model: Warehouse, as: 'warehouse', attributes: ['name', 'address'], required: false },
      { model: User, as: 'creator', attributes: ['realName', 'username'], required: false },
      { model: User, as: 'firstConfirmer', attributes: ['realName', 'username'], required: false },
      { model: User, as: 'secondConfirmer', attributes: ['realName', 'username'], required: false },
      {
        model: StocktakeItem,
        as: 'items',
      },
    ],
  });

  if (!stocktake) {
    throw new NotFoundError('盘库记录不存在');
  }

  // Format export data
  const stObj = stocktake.toJSON();
  const exportData = {
    stocktakeNo: stObj.stocktakeNo,
    title: stObj.title,
    warehouseName: stObj.warehouseName,
    status: stObj.status,
    startTime: stObj.startTime,
    endTime: stObj.endTime,
    totalProfitQuantity: stObj.totalProfitQuantity,
    totalProfitAmount: stObj.totalProfitAmount,
    totalLossQuantity: stObj.totalLossQuantity,
    totalLossAmount: stObj.totalLossAmount,
    firstConfirmedBy: stObj.firstConfirmer?.realName,
    firstConfirmedAt: stObj.firstConfirmedAt,
    secondConfirmedBy: stObj.secondConfirmer?.realName,
    secondConfirmedAt: stObj.secondConfirmedAt,
    createdBy: stObj.creator?.realName,
    createdAt: stObj.createdAt,
    remark: stObj.remark,
    items: stObj.items?.map(item => ({
      sku: item.sku,
      productName: item.productName,
      spec: item.spec,
      unit: item.unit,
      systemQuantity: item.systemQuantity,
      actualQuantity: item.actualQuantity,
      difference: item.difference,
      differenceType: item.differenceType === 'profit' ? '盘盈' : item.differenceType === 'loss' ? '盘亏' : '无差异',
      unitPrice: item.unitPrice,
      totalAmount: item.totalAmount,
      remark: item.remark,
    })) || [],
  };

  res.json({ data: exportData, message: '导出成功' });
}));

module.exports = router;
